#+AUTHOR: AnAnnoyinGoose

* ToC
- [[#Scripts][Scripts]]
  - [[#send][send]]
  - [[#archive_all][archive_all]]
  - [[#archJavaSwitcher][archJavaSwitcher]]
  - [[#tcd][tcd]]
  - [[#remotebuild][remotebuild]]
  - [[#fix-touch][fix-touch]]
* Scripts
** send
*** Dependencies
  - ssh
  - scp
  - sshpass
*** Description
Uses sshpass and a 'key' to send a file to a remote server.
The key is the ssh password encrypted with gpg.
*** Key Creation
#+begin_src bash
touch .sshpwd
echo "sshkey" >> .sshpwd
gpg -c .sshpwd
rm .sshpwd
#+end_src
!! Make sure to leave the key in the same directory as the script !!
*** Usage
#+begin_src bash
./send.sh <file> <user@host:/dir/dir>
#+end_src
If you don't have the dependencies, the script will prompt you and install ssh (OpenSSH) and sshpass if your OS is:
- Debian/Ubuntu
- CentOS
- Fedora
- Archlinux (the best :) )
otherwise it'll exit 1

** archive_all
*** Dependencies
  - tar
  - openssl
*** Description
Archives all files in the current directory.
*** Usage
#+begin_src bash
./archive_all.sh [password]
#+end_src
The program will gather all images, videos, and txt files in the current directory.
It will encrypt them with OpenSSL if a password is provided.

** archJavaSwitcher
*** Dependencies
  - rofi
  - archlinux-java
*** Description
Uses 'archlinux-java status' to get the list of all Java versions and passes it to rofi.
The script will need sudo password to work.
*** Usage
#+begin_src bash
./archJavaSwitcher
#+end_src

** tcd
*** Dependencies
  - none :)
*** Description
TCD [temp change directory]
Allows running commands in a different directory.
The command will create the directory if it doesn't exist!
*** Usage
#+begin_src bash
./tcd build make; ./build/[program]
# or
./tcd ~/.config/nvim ls -l
#+end_src

** remotebuild
*** Description
Remotebuild
Allows you to build a project on a different machine.
With the -r flag, you can also run the built program with active I/O, and then a log file (`log.[date|time].rb`) will be created and sent back to the local machine.

### Standard Usage
Without the `-r` flag, the `remotebuild` script sends a directory to a remote machine, executes a build script, and retrieves the `build` folder:
#+begin_src bash
remotebuild.sh <remote machine> <dest> <build.sh> <directory-to-send>
#+end_src

### Usage with the `-r` flag
With the `-r` flag, after building the project, the script runs the program on the remote machine, captures active I/O, and sends the log file back to the local machine:
#+begin_src bash
remotebuild.sh -r <remote machine> <dest> <build.sh> <directory-to-send> <run-command>
#+end_src

### Example
Building and running a project with active I/O on a remote machine:
#+begin_src bash
remotebuild.sh -r user@remotehost /home/user/project build.sh ./src "make && ./build/myprogram"
#+end_src

This command will:
1. Send the `./src` directory to `/home/user/project` on the remote machine `user@remotehost`.
2. Run the `build.sh` script.
3. Execute `make && ./build/myprogram` on the remote machine.
4. Capture the output and save it in `log.[date|time].rb` and send it back to the local machine.

** fix-touch
*** Dependencies
  - xrandr
  - xinput
*** Description
Fixes touchscreen calibration issues and rotates the display.
The script rotates the primary display to the right and applies a coordinate transformation matrix to the touchscreen.
*** Usage
#+begin_src bash
./fix-touch.sh
#+end_src
The script sets a specific touchscreen calibration and rotates the display. It requires the touchscreen and display names to be correctly identified.
