#+AUTHOR: AnAnnoyinGoose

* ToC
- [[#Scripts][Scripts]]
  - [[#send][send]]
  - [[#archive_all][archive_all]]
  - [[#archJavaSwitcher][archJavaSwitcher]]
  - [[#tcd][tcd]]
* Scripts
** send
*** Dependencies
  - ssh
  - scp
  - sshpass
*** Description
Uses sshpass and a 'key' to send a file to a remote server.
The key the ssh password encrypted with gpg.
*** Key Creation
#+begin_src bash
touch .sshpwd
echo "sshkey" >> .sshpwd
gpg -c .sshpwd
rm .sshpwd
#+end_src
!! Make sure to leave the key in the same directory as the script !!
*** Usage
#+begin_src bash
./send.sh <file> <user@host:/dir/dir>
#+end_src
If you dont have the dependencies the script will prompt you and install ssh (open ssh) and sshpass if your os is:
- Debian/Ubuntu
- CentOS
- Fedora
- Archlinux ( the best :) )
otherwise it'll exit 1



** archive_all
*** Dependicies
  - tar
  - openssl
*** Description
Archives all files in the current directory.
*** Usage
#+begin_src bash
./archive_all.sh [password]
#+end_src
the program will get the all images, videos, and txt files in the current directory.
And will encrypt the with openssl if wanted.
 


** archJavaSwitcher
*** Dependicies
  - rofi
  - archlinux-java
*** Description
Uses 'archlinux-java status' to get the list of all java versions and passes it to rofi.
The sh script will need sudo pswd to work.
*** Usage
#+begin_src bash
./archJavaSwitcher
#+end_src






** tcd
*** Dependicies
- none :)
*** Description
TCD [temp change directory] \\

Allows running commands in a different directory. \\

The command will create the directory if it doesn't exist!
*** Usage
#+begin_src bash
./tcd build make; ./build/[program]
# or
./tcd ~/.config/nvim ls -l
#+end_src
